<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateProgramFile>false</GenerateProgramFile>
    <IsPackable>false</IsPackable>
    <DefineConstants>FABLE_COMPILER;FABLE_COMPILER_PYTHON</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\ReferenceObjects.fs" Link="ReferenceObjects.fs" />
    <Compile Include="..\FrontmatterTests.fs" Link="FrontmatterTests.fs" />
    <Compile Include="..\YamlTests.fs" Link="YamlTests.fs" />
    <Compile Include="..\ConfigYamlTests.fs" Link="ConfigYamlTests.fs" />
    <Compile Include="..\JsonTests.fs" Link="JsonTests.fs" />
    <Compile Include="..\Main.fs" Link="Main.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Python" Version="5.4.0" />
    <PackageReference Include="Fable.Pyxpecto" Version="2.0.0" />
    <ProjectReference Include="..\..\..\src\ValidationPackage.Codecs\targets\ValidationPackage.Codecs.Python.fsproj" />
  </ItemGroup>

</Project>
